### ISSUE TITLE
Wrong db installation path

### ISSUE THREAD

**Issue by edoardottt** [Brum3ns/firefly#9] opened 2023-09-29 14:46 UTC
installed using
```console
go install -v github.com/Brum3ns/firefly/cmd/firefly@v1.2.0
```
executed
```console
firefly
```

got
```console                             
   / __7 o          / _7/¯7  
  / _7 /¯7 /¯_7¯-_)/ _7/ /\¯\/7
 /_/  /_/ /_/ \__7/_/ /_/  ) /
                          /_/
                                (v1.1.0)
   By: @yeswehack : Brumens
[INF]  The 'db' folder containing all the resources for Firefly to work will be stored at: /home/edoardottt/.config/firefly//db/ 
[INPUT] Write "ok" to confirm:
```

**Comment by Brum3ns** [comment] 2023-09-29 15:16
Hey edoardottt,
I am not sure what the problem is, database (db) that contains the default payload lists and resources will be added to : `/home/edoardottt/.config/firefly//db/`

If this folder do not exist it will create a new one for you.

Regards,
Brumens

**Comment by Brum3ns** [comment] 2023-09-29 15:17
I can see another issue. It appears that the go command did not install the latest version (v1.2.0) which is strange

**Comment by Brum3ns** [comment] 2023-09-29 15:19
I discovered the issue with the release, it's invalid linked. I will fix it asap

**Comment by edoardottt** [comment] 2023-09-29 18:59
there is an additional slash, it should be `home/edoardottt/.config/firefly/db/`

**Comment by Brum3ns** [comment] 2023-09-30 12:24
I understand what you mean. Yes, it has a double slash but it does not affect the path Linux ignores double slashes that are in line and normalizes it to the path automatically. The path with doubleslash is threated exacly like `home/edoardottt/.config/firefly/db/` with a single slash in Linux.


The reason this happens here is that the global variables containing the configuration paths/endpoints all contain a slash at the end to always make sure it is a folder. This ensures that any future development is safe and does not interact with other directories next to these folders.

An example if I do not make sure to add the end slash in a global variable and a future development provide a code that is poorly written and could cause damage:

```golang
GLOBAL_CONFIG := "/config"

newFile, _:= os.Create(GLOBAL_CONFIG+"test.txt")
```

This would result in that I write to a new file named `/configtest.txt` instead of `test.txt`. To minimize bugs, the slash is added to the end of a global variable to ensure that these bugs do not appear and do not affect the actual path of the global variable value. The extra slash you see is because sometimes two global variables is chained like: 
```golang
GLOBAL_CONFIG := "/config/"
GLOBAL_RESOURCE := GLOBAL_CONFIG + "/resources/"
GLOBAL_WORDLIST :=  GLOBAL_RESOURCE  + "/wordlist/"
```
The reason it is written like this and not just `/config/resources` or `/config/wordlist` is that if any of these global variables are moved in the future (_likely not, but just in case..._), all other global variables will follow and remain valid.

**Comment by edoardottt** [comment] 2023-10-01 07:08
I got what you mean, you could use [`filepath.Join`](https://pkg.go.dev/path/filepath#Join) in this case.

example: https://go.dev/play/p/2Fpb_vJzvSb

**Comment by Brum3ns** [comment] 2023-10-04 11:46
Thanks for the share I may consider checking on this in the future but meanwhile it do not make any issue to the functionality so I will close this as fixed.

Thanks for the feedback!

**Closed as completed by Brum3ns** 2023-10-04 11:46 UTC
